//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileRenamerDiff.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FileRenamerDiff.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Adding serial numbers に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AddingSerial_AddingSerialNumber {
            get {
                return ResourceManager.GetString("AddingSerial_AddingSerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Genarated Pattern に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AddingSerial_GenaratedPattern {
            get {
                return ResourceManager.GetString("AddingSerial_GenaratedPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Inverse:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AddingSerial_Inverse {
            get {
                return ResourceManager.GetString("AddingSerial_Inverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset per Folder:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AddingSerial_ResetPerFolder {
            get {
                return ResourceManager.GetString("AddingSerial_ResetPerFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start Number:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AddingSerial_StartNumber {
            get {
                return ResourceManager.GetString("AddingSerial_StartNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Step:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AddingSerial_Step {
            get {
                return ResourceManager.GetString("AddingSerial_Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Zero-Padding Digits:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AddingSerial_ZeroPaddingDigits {
            get {
                return ResourceManager.GetString("AddingSerial_ZeroPaddingDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you want to clear table? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Alert_ConfirmClearBody {
            get {
                return ResourceManager.GetString("Alert_ConfirmClearBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Confirm に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Alert_ConfirmClearHead {
            get {
                return ResourceManager.GetString("Alert_ConfirmClearHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FAILED to save rename. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Alert_FailSaveRename {
            get {
                return ResourceManager.GetString("Alert_FailSaveRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FAILED to save settings. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Alert_FailSaveSetting {
            get {
                return ResourceManager.GetString("Alert_FailSaveSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Some file names are DUPLICATED. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Alert_FileNamesDuplicated {
            get {
                return ResourceManager.GetString("Alert_FileNamesDuplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The output file name contains invalid file-name characters. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Alert_InvalidFileName {
            get {
                return ResourceManager.GetString("Alert_InvalidFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Files could not be found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Alert_NotFoundFileBody {
            get {
                return ResourceManager.GetString("Alert_NotFoundFileBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add the directory name before the extension に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_AddDirectoryNameBeforeExtension {
            get {
                return ResourceManager.GetString("Common_AddDirectoryNameBeforeExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add the directory name at the beginning に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_AddDirectoryNameBeginning {
            get {
                return ResourceManager.GetString("Common_AddDirectoryNameBeginning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add three &apos;0&apos; to the number (three-digit zero padding 1/2) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_AddThreeZero {
            get {
                return ResourceManager.GetString("Common_AddThreeZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete all characters に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_DeleteAll {
            get {
                return ResourceManager.GetString("Common_DeleteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete characters before the extension に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_DeleteBeforeExtension {
            get {
                return ResourceManager.GetString("Common_DeleteBeforeExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete extension に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_DeleteExtention {
            get {
                return ResourceManager.GetString("Common_DeleteExtention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete &quot;ABC&quot; in a case-insensitive に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_DeleteIgnoreCase {
            get {
                return ResourceManager.GetString("Common_DeleteIgnoreCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete spaces before a symbol に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_DeleteWhitespacesBeforeSymbol {
            get {
                return ResourceManager.GetString("Common_DeleteWhitespacesBeforeSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete whitespaces from the head and tail に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_DeleteWhitespacesHeadTail {
            get {
                return ResourceManager.GetString("Common_DeleteWhitespacesHeadTail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete the spaces inside the brackets に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_DeleteWhitespacesInsideBrace {
            get {
                return ResourceManager.GetString("Common_DeleteWhitespacesInsideBrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete the &quot;copy&quot; tag in Windows に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_DeleteWindowsCopyTag {
            get {
                return ResourceManager.GetString("Common_DeleteWindowsCopyTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete Windows &quot;(number)&quot; tag に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_DeleteWindowsNumberTag {
            get {
                return ResourceManager.GetString("Common_DeleteWindowsNumberTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete the &quot;shortcut&quot; tag in Windows に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_DeleteWindowsShortcutTag {
            get {
                return ResourceManager.GetString("Common_DeleteWindowsShortcutTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Insert &quot;XYZ&quot; as the third character に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_InsertIndex {
            get {
                return ResourceManager.GetString("Common_InsertIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reduce spaces to a single space に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_ReduceWhiteSpace {
            get {
                return ResourceManager.GetString("Common_ReduceWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Replace extension with &quot;ABC&quot; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_ReplaceAllExtentionToABC {
            get {
                return ResourceManager.GetString("Common_ReplaceAllExtentionToABC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Convert all letters and numbers to Half-width characters に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_ReplaceHalf {
            get {
                return ResourceManager.GetString("Common_ReplaceHalf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Convert all Half-width Katakana to full-width に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_ReplaceHanKana {
            get {
                return ResourceManager.GetString("Common_ReplaceHanKana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Replace &quot;ABC&quot; with &quot;x&quot; in a case-insensitive に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_ReplaceIgnoreCase {
            get {
                return ResourceManager.GetString("Common_ReplaceIgnoreCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Convert all text to lower-case に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_ReplaceLowerCase {
            get {
                return ResourceManager.GetString("Common_ReplaceLowerCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Convert all text to title-case に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_ReplaceTitleCase {
            get {
                return ResourceManager.GetString("Common_ReplaceTitleCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Convert umlauts to plain-ascii characters に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_ReplaceUmulaut {
            get {
                return ResourceManager.GetString("Common_ReplaceUmulaut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Convert all text to upper-case に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_ReplaceUpperCase {
            get {
                return ResourceManager.GetString("Common_ReplaceUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Replace whitespace with &apos;_&apos; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_ReplaceWhiteSpacesWithUnderbar {
            get {
                return ResourceManager.GetString("Common_ReplaceWhiteSpacesWithUnderbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Convert all letters and numbers to Full-width characters に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_ReplaceWide {
            get {
                return ResourceManager.GetString("Common_ReplaceWide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Surround &quot;ABC&quot; with [] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_SurroundWithSqureBrackets {
            get {
                return ResourceManager.GetString("Common_SurroundWithSqureBrackets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reduce the number to three digits (padding of three zeros 2/2) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_TakeNumberThreeDigits {
            get {
                return ResourceManager.GetString("Common_TakeNumberThreeDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mark with change
        ///A check mark is displayed if there are any changes. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Grid_Changed {
            get {
                return ResourceManager.GetString("Grid_Changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mark with duplicate
        ///If there are duplicates, a duplicate mark is displayed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Grid_Conflicted {
            get {
                return ResourceManager.GetString("Grid_Conflicted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Created Date に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Grid_CreatedDate {
            get {
                return ResourceManager.GetString("Grid_CreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Date modified に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Grid_DateModified {
            get {
                return ResourceManager.GetString("Grid_DateModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Directory に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Grid_Directory {
            get {
                return ResourceManager.GetString("Grid_Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1. Target file specification
        ///You can drag and drop files here, or &quot;Search Files&quot; from a specific directory.
        ///
        ///2. Set rename pattern
        ///Set the Delete/Replace pattern from &quot;Settings&quot;.
        ///
        ///3. Confirm rename
        ///Execute &quot;DRY RUN&quot; to confirm the renaming.
        ///
        ///4. Execute rename.
        ///Execute &quot;SAVE&quot; to rename the actual file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Grid_DropDescription {
            get {
                return ResourceManager.GetString("Grid_DropDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File Type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Grid_FileType {
            get {
                return ResourceManager.GetString("Grid_FileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NEW File Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Grid_NewText {
            get {
                return ResourceManager.GetString("Grid_NewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OLD File Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Grid_OldText {
            get {
                return ResourceManager.GetString("Grid_OldText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Grid_Size {
            get {
                return ResourceManager.GetString("Grid_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select the target directory from the left button, or Drag-Drop. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Hint_SelectTargetDirectory {
            get {
                return ResourceManager.GetString("Hint_SelectTargetDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   After saving the rename, some files were removed from the list. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Info_FileRemoved {
            get {
                return ResourceManager.GetString("Info_FileRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings were reset. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Info_SettingsReset {
            get {
                return ResourceManager.GetString("Info_SettingsReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ## 3rd Party Libraries / Icons
        ///
        ///Following codes / libraries make it happen, thanks for their work.
        ///
        ///### ReactiveProperty
        ///
        ///Authors: neuecc xin9le okazuki
        ///
        ///Project Site: https://github.com/runceel/ReactiveProperty
        ///
        ///License: https://licenses.nuget.org/MIT
        ///
        ///### Utf8Json
        ///
        ///Authors: neuecc
        ///
        ///Project Site: https://github.com/neuecc/Utf8Json/
        ///
        ///License: https://licenses.nuget.org/MIT
        ///
        ///### DiffPlex
        ///
        ///Authors: Matthew Manela
        ///
        ///Project Site: https://github.com/mmanela/diffplex/
        ///
        ///License: https://g [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add Files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_AddFiles {
            get {
                return ResourceManager.GetString("Menu_AddFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Directly specify the files to be renamed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_AddFilesHint {
            get {
                return ResourceManager.GetString("Menu_AddFilesHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DRY RUN に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_DryRun {
            get {
                return ResourceManager.GetString("Menu_DryRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change only on the list below, do not save to storage yet. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_DryRunHint {
            get {
                return ResourceManager.GetString("Menu_DryRunHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SAVE に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_Save {
            get {
                return ResourceManager.GetString("Menu_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save to storage. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_SaveHint {
            get {
                return ResourceManager.GetString("Menu_SaveHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search Files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_SearchFiles {
            get {
                return ResourceManager.GetString("Menu_SearchFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search files in the target directory on the left. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_SearchFilesHint {
            get {
                return ResourceManager.GetString("Menu_SearchFilesHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ADD に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Setting_Add {
            get {
                return ResourceManager.GetString("Setting_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Regular Expression に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Setting_AsExpression {
            get {
                return ResourceManager.GetString("Setting_AsExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CLEAR ALL に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Setting_ClearAll {
            get {
                return ResourceManager.GetString("Setting_ClearAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A collection of common patterns に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Setting_CommonPatterns {
            get {
                return ResourceManager.GetString("Setting_CommonPatterns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete Texts に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Setting_DeleteTexts {
            get {
                return ResourceManager.GetString("Setting_DeleteTexts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Text に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Setting_DeleteTextTarget {
            get {
                return ResourceManager.GetString("Setting_DeleteTextTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Export Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Setting_ExportSettingFile {
            get {
                return ResourceManager.GetString("Setting_ExportSettingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File Search に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Setting_FileSearch {
            get {
                return ResourceManager.GetString("Setting_FileSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Setting_FileTypeDirectory {
            get {
                return ResourceManager.GetString("Setting_FileTypeDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Setting_FileTypeFile {
            get {
                return ResourceManager.GetString("Setting_FileTypeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hidden に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Setting_FileTypeHidden {
            get {
                return ResourceManager.GetString("Setting_FileTypeHidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ignore Directory に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Setting_IgnoreDirectory {
            get {
                return ResourceManager.GetString("Setting_IgnoreDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ignore Extensions に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Setting_IgnoreExtensions {
            get {
                return ResourceManager.GetString("Setting_IgnoreExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File types to rename に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Setting_IgnoreFileTypes {
            get {
                return ResourceManager.GetString("Setting_IgnoreFileTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Import Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Setting_ImportSettingFile {
            get {
                return ResourceManager.GetString("Setting_ImportSettingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create a log file when renaming に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Setting_IsCreateRenameLog {
            get {
                return ResourceManager.GetString("Setting_IsCreateRenameLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rename file extensions as well に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Setting_IsRenameExt {
            get {
                return ResourceManager.GetString("Setting_IsRenameExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Other に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Setting_Other {
            get {
                return ResourceManager.GetString("Setting_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Replace Patterns に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Setting_ReplacePatterns {
            get {
                return ResourceManager.GetString("Setting_ReplacePatterns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Replace Text に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Setting_ReplaceText {
            get {
                return ResourceManager.GetString("Setting_ReplaceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Target Text に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Setting_ReplaceTextTarget {
            get {
                return ResourceManager.GetString("Setting_ReplaceTextTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset ALL Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Setting_ResetAllSetting {
            get {
                return ResourceManager.GetString("Setting_ResetAllSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search Sub Directories に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Setting_SearchSubDirectories {
            get {
                return ResourceManager.GetString("Setting_SearchSubDirectories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Setting_SettingTab {
            get {
                return ResourceManager.GetString("Setting_SettingTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   -copy に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Windows_CopyFileSuffix {
            get {
                return ResourceManager.GetString("Windows_CopyFileSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   - Shortcut に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Windows_ShortcutFileSuffix {
            get {
                return ResourceManager.GetString("Windows_ShortcutFileSuffix", resourceCulture);
            }
        }
    }
}
