//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileRenamerDiff.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FileRenamerDiff.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   FAILED to save rename. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Alert_FailSaveRename {
            get {
                return ResourceManager.GetString("Alert_FailSaveRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FAILED to save settings. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Alert_FailSaveSetting {
            get {
                return ResourceManager.GetString("Alert_FailSaveSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Some fileNames are DUPLICATED. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Alert_FileNamesDuplicated {
            get {
                return ResourceManager.GetString("Alert_FileNamesDuplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The output file name contains invalid file-name characters. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Alert_InvalidFileName {
            get {
                return ResourceManager.GetString("Alert_InvalidFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Changed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Grid_Changed {
            get {
                return ResourceManager.GetString("Grid_Changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Duplicated に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Grid_Conflicted {
            get {
                return ResourceManager.GetString("Grid_Conflicted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Created Date に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Grid_CreatedDate {
            get {
                return ResourceManager.GetString("Grid_CreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Date modified に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Grid_DateModified {
            get {
                return ResourceManager.GetString("Grid_DateModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Directory に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Grid_Directory {
            get {
                return ResourceManager.GetString("Grid_Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NEW File Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Grid_NewText {
            get {
                return ResourceManager.GetString("Grid_NewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OLD File Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Grid_OldText {
            get {
                return ResourceManager.GetString("Grid_OldText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Grid_Size {
            get {
                return ResourceManager.GetString("Grid_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings were reset. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Info_SettingsReset {
            get {
                return ResourceManager.GetString("Info_SettingsReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ## 3rd Party Libraries / Icons
        ///
        ///Following codes / libraries make it happen, thanks for their work.
        ///
        ///### ReactiveProperty
        ///
        ///Authors: neuecc xin9le okazuki
        ///
        ///Project Site: https://github.com/runceel/ReactiveProperty
        ///
        ///License: https://licenses.nuget.org/MIT
        ///
        ///### MessagePack
        ///
        ///Authors: neuecc, aarnott
        ///
        ///Project Site: https://github.com/neuecc/MessagePack-CSharp
        ///
        ///License: https://licenses.nuget.org/MIT
        ///
        ///### DiffPlex
        ///
        ///Authors: Matthew Manela
        ///
        ///Project Site: https://github.com/mmanela/diffplex/
        ///
        ///License: https://github [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DRY RUN に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_DryRun {
            get {
                return ResourceManager.GetString("Menu_DryRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SAVE に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_Save {
            get {
                return ResourceManager.GetString("Menu_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search Files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_SearchFiles {
            get {
                return ResourceManager.GetString("Menu_SearchFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ADD に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Setting_Add {
            get {
                return ResourceManager.GetString("Setting_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   As
        ///REGEXP に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Setting_AsExpression {
            get {
                return ResourceManager.GetString("Setting_AsExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CLEAR ALL に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Setting_ClearAll {
            get {
                return ResourceManager.GetString("Setting_ClearAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete Texts に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Setting_DeleteTexts {
            get {
                return ResourceManager.GetString("Setting_DeleteTexts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Text に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Setting_DeleteTextTarget {
            get {
                return ResourceManager.GetString("Setting_DeleteTextTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File Search に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Setting_FileSearch {
            get {
                return ResourceManager.GetString("Setting_FileSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ignore Directory に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Setting_IgnoreDirectory {
            get {
                return ResourceManager.GetString("Setting_IgnoreDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ignore Extensions に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Setting_IgnoreExtensions {
            get {
                return ResourceManager.GetString("Setting_IgnoreExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Other に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Setting_Other {
            get {
                return ResourceManager.GetString("Setting_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Replace Patterns に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Setting_ReplacePatterns {
            get {
                return ResourceManager.GetString("Setting_ReplacePatterns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Replace Text に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Setting_ReplaceText {
            get {
                return ResourceManager.GetString("Setting_ReplaceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Target Text に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Setting_ReplaceTextTarget {
            get {
                return ResourceManager.GetString("Setting_ReplaceTextTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset ALL Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Setting_ResetAllSetting {
            get {
                return ResourceManager.GetString("Setting_ResetAllSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search Sub Directories に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Setting_SearchSubDirectories {
            get {
                return ResourceManager.GetString("Setting_SearchSubDirectories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Setting_SettingTab {
            get {
                return ResourceManager.GetString("Setting_SettingTab", resourceCulture);
            }
        }
    }
}
